completed express-error-handling exercise, avallon smith
avallonsmith/rc0322-code-solutions pull request #110
Opened 2022-05-25 23:06 UTC by avallonsmith

![image](https://user-images.githubusercontent.com/96964291/170383660-47347749-fec0-4e36-be30-e4f40c1a6882.png)

2022-05-25 23:51 UTC, scbowler approved these changes
Looks great, just missed one `ClientError`. Let me know if you have any questions.

2022-05-25 23:51 UTC, scbowler commented on express-error-handling/server/index.js
> +    return;
Should be a `ClientError` here

2022-05-25 23:51 UTC, scbowler requested changes
Ooops didn't mean to approve

2022-05-26 03:00 UTC, avallonsmith commented on express-error-handling/server/index.js
> +    return;
Everything has been updated, apologies for the inconvenience!

2022-05-26 17:58 UTC, scbowler approved these changes
Great job implementing the feedback, looks good! 👍

2022-05-26 21:56 UTC, merged