completed sgt-back-end exercise, avallon smith
avallonsmith/rc0322-code-solutions pull request #117
Opened 2022-05-27 22:38 UTC by avallonsmith

![image](https://user-images.githubusercontent.com/96964291/170797143-75b23f49-f156-4bec-be06-05301a25486c.png)
![image](https://user-images.githubusercontent.com/96964291/170797151-0d455d2f-c2c9-4166-9fee-d19c2864a49b.png)
![image](https://user-images.githubusercontent.com/96964291/170797159-3e32ec28-3978-425d-8673-7c14502902e5.png)

2022-06-23 00:25 UTC, thebearingedge requested changes

2022-06-23 00:25 UTC, thebearingedge commented on sgt-back-end/index.js
> +    });
Be sure to include a `return` statement after each of these error responses to prevent the server from attempting to respond twice to the same request (and crashing).

2022-06-28 19:53 UTC, avallonsmith commented on sgt-back-end/index.js
> +    });
Return statements have been added, apologies for any inconveniences!
![image](https://user-images.githubusercontent.com/96964291/176272898-59c87540-e023-4002-b728-550e99c7a897.png)

2022-06-28 19:57 UTC, scbowler requested changes
Looking better! Just missed a couple spots. Let me know if you have any questions.

2022-06-28 19:57 UTC, scbowler commented on sgt-back-end/index.js
> +  }
This part looks great!

2022-06-28 19:57 UTC, scbowler commented on sgt-back-end/index.js
> +    });
You need to do the same thing here

2022-06-28 20:31 UTC, scbowler approved these changes
Looks good! 👍

2022-06-28 21:09 UTC, merged