completed sql-select exercise, avallon smith
avallonsmith/rc0322-code-solutions pull request #82
Opened 2022-05-11 21:20 UTC by avallonsmith

![image](https://user-images.githubusercontent.com/96964291/167949625-c957e112-a362-4d26-945f-171199b2bc1d.png)

2022-05-11 22:38 UTC, scbowler requested changes
Looking good, just a couple updates needed. Let me know if you have any questions.

2022-05-11 22:38 UTC, scbowler commented on sql-select/actor-forty.sql
> +  where "actorId"= '40';
Numbers shouldn't be in quotes

2022-05-11 22:38 UTC, scbowler commented on sql-select/expensive-films.sql
> +  order by "replacementCost" asc,
Here you want the sort order to be `desc`

2022-05-11 22:38 UTC, scbowler commented on sql-select/inactive-customers.sql
> +  order by "false" desc;
This should be `where "isActive" = false;` No `order by`  needed for this one.

2022-05-12 16:56 UTC, avallonsmith commented on sql-select/inactive-customers.sql
> +  order by "false" desc;
![image](https://user-images.githubusercontent.com/96964291/168128723-904338bf-11c3-4585-b40f-a625b7e0fbb6.png)
corrected!

2022-05-12 16:57 UTC, avallonsmith commented on sql-select/actor-forty.sql
> +  where "actorId"= '40';
![image](https://user-images.githubusercontent.com/96964291/168128860-13c41790-8867-4ef8-a82b-29faf0ce1183.png)
corrected!

2022-05-12 17:05 UTC, scbowler approved these changes
Great job implementing the feedback, looks good! 👍

2022-05-17 19:16 UTC, merged