completed sql-insert exercise, avallon smith
avallonsmith/rc0322-code-solutions pull request #83
Opened 2022-05-11 22:46 UTC by avallonsmith

![image](https://user-images.githubusercontent.com/96964291/167959492-6df6bfe8-264a-42af-9c55-ce1133022140.png)
![image](https://user-images.githubusercontent.com/96964291/167959538-bf831249-67a3-4578-a56a-936b15b1e493.png)

2022-05-11 22:54 UTC, scbowler requested changes
Really close! Just 1 update needed.

2022-05-11 22:54 UTC, scbowler commented on sql-insert/insert-actor.sql
> +values ('Johnny', 'Depp')
👍

2022-05-11 22:54 UTC, scbowler commented on sql-insert/insert-languages.sql
> +values ('HTML', 'CSS', 'JavaScript')
Each row to insert needs to be in separate parentheses, so it should be:
```SQL

insert into "languages"("name")
values
  ('HTML'), 
  ('CSS'),
  ('JavaScript')
returning *;
```

2022-05-11 23:32 UTC, avallonsmith commented on sql-insert/insert-languages.sql
> +values ('HTML', 'CSS', 'JavaScript')
Shoot. I updated that in the pagila query but forgot to in the code, I'll fix it ASAP, sorry about that!

2022-05-12 17:05 UTC, scbowler approved these changes
Great job implementing the feedback, looks good! 👍

2022-05-17 19:15 UTC, merged